# Generated by Django 5.1.7 on 2025-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemontApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
